### ISSUE TITLE
allurectl watch ignored variable ALLURE_RESULTS and dont upload results to allure testops

### ISSUE THREAD

**Issue by allanian** [allure-framework/allurectl#13]
Hello, we're created gitlab job for our tests.
allurectl watch should execute our tests and upload report to our allure testops in real time, but its never like that for us, can you help please.
1) allurectl watch - allways saving reports to ./build/allure-reports and i cant change it with my variable  ALLURE_RESULTS or --results arg.
2) allurectl watch execute our gradle test, but dont send it to allure testops, when we do it with this steps:
```
   a) gradle test -Dbrowser=${BROWSER} -DbrowserVersion=${BROWSER_VERSION} -DbrowserSize=${BROWSER_SIZE} -DbrowserMobileView=${BROWSER_MOBILE} -DremoteDriverUrl=$MOON_URL -DvideoStorage= -Dthreads=${THREADS}
   b) allurectl upload --endpoint $ALLURE_ENDPOINT --token $ALLURE_TOKEN --project-id $ALLURE_PROJECT_ID --launch-name "Local PC manual launch" build/allure-results
```
its working fine.

.gitlab-ci.yaml
```
variables:
  # ALLURE
  ALLURE_PROJECT_ID: 1
  ALLURE_LAUNCH_NAME: "${CI_PROJECT_NAME} - ${CI_COMMIT_SHORT_SHA}"
  ALLURE_LAUNCH_TAGS: "regular, ${CI_COMMIT_REF_NAME}"
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_RESULTS: "allure-report-dir"
test:
  stage: test
  image: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG-app:latest
  script:
    - gradle wrapper
    - gradle clean
    - ./allurectl watch -- gradle test -Dbrowser=${BROWSER} -DbrowserVersion=${BROWSER_VERSION} -DbrowserSize=${BROWSER_SIZE} -DbrowserMobileView=${BROWSER_MOBILE} -DremoteDriverUrl=$MOON_URL -DvideoStorage= -Dthreads=${THREADS} -Dselenide.timeout=17000
  tags: 
    - docker
```
